[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "abc"
version = "1"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]

[tool.hatch.build.targets.wheel]
packages = ["src/abc"]
